// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Separate_K_rpkm_new1
Rcpp::List Separate_K_rpkm_new1(Rcpp::NumericVector y, const int ROUNDS, const int Zcut, const int k, double err);
RcppExport SEXP _LTMGSCA_Separate_K_rpkm_new1(SEXP ySEXP, SEXP ROUNDSSEXP, SEXP ZcutSEXP, SEXP kSEXP, SEXP errSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< const int >::type ROUNDS(ROUNDSSEXP);
    Rcpp::traits::input_parameter< const int >::type Zcut(ZcutSEXP);
    Rcpp::traits::input_parameter< const int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type err(errSEXP);
    rcpp_result_gen = Rcpp::wrap(Separate_K_rpkm_new1(y, ROUNDS, Zcut, k, err));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LTMGSCA_Separate_K_rpkm_new1", (DL_FUNC) &_LTMGSCA_Separate_K_rpkm_new1, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_LTMGSCA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
